---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aepps-ingress
  namespace: hackmd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hackmd.aepps.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hackmd
          servicePort: 3000