---


# Access-Control-Allow-Origin "*"
# Access-Control-Allow-Headers "Authorization, Content-Type"
# Access-Control-Allow-Methods "GET, OPTIONS, POST"
# Access-Control-Expose-Headers "Content-Security-Policy, Location"
# Access-Control-Max-Age "600"



apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: all-sdk-testnet-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: sdk-testnet.aepps.com
    http:
      paths:
      - path: /
        backend:
          serviceName: epoch-uber-proxy
          servicePort: http

  - host: "*.sdk-testnet.aepps.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: epoch-uber-proxy
          servicePort: http

        