apiVersion: apps/v1
kind: Deployment
metadata:
  name: aepp-explorer
spec:
  selector:
    matchLabels:
      app: aepp-explorer
  replicas: 1
  template:
    metadata:
      labels:
        app: aepp-explorer
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: aepp-explorer
        image: 166568770115.dkr.ecr.eu-central-1.amazonaws.com/aepp-explorer:bfbc816
        ports:
        - name: web
          containerPort: 80
        imagePullPolicy: Always
        env:
          - name: VUE_APP_EPOCH_URL
            value: https://sdk-testnet.aepps.com
---
apiVersion: v1
kind: Service
metadata:
  name: aepp-explorer-service
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: aepp-explorer
    

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aepp-explorer
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: aepp-explorer
  endpoints:
  - port: web
