apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aepp-trader
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aepp-trader
            image: 166568770115.dkr.ecr.eu-central-1.amazonaws.com/aeternity/aepp-trader:0.1.0
            # imagePullPolicy: Always
            env:
            - name: TOPLIMIT
              value: "10"
          restartPolicy: OnFailure