apiVersion: apps/v1
kind: Deployment
metadata:
  name: aepp-contracts
spec:
  selector:
    matchLabels:
      app: aepp-contracts
  replicas: 1
  template:
    metadata:
      labels:
        app: aepp-contracts
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: aepp-contracts
        image: 166568770115.dkr.ecr.eu-central-1.amazonaws.com/aeternity/aepp-contracts:0.24.0-1.0.0
        ports:
        - name: web
          containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: aepp-contracts-service
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: aepp-contracts
    

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aepp-contracts
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: aepp-contracts
  endpoints:
  - port: web
