---
apiVersion: v1
kind: ConfigMap
metadata:
  name: main-epoch-config
data:
  epoch-master.yaml: |
    ---
    http:
      external:
        port: 3013
      internal:
        port: 3113
        listen_address: 0.0.0.0
      debug: false

    websocket:
      channel:
        port: 3014
        listen_address: 0.0.0.0

    chain:
      persist: true

    mining:
      beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
      autostart: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-epoch-master
spec:
  selector:
    matchLabels:
      app: main-epoch-master
  replicas: 1
  template:
    metadata:
      labels:
        app: main-epoch-master
    spec:
      containers:
      - name: main-epoch-master
        image: aeternity/epoch:v1.0.0
        ports:
        - containerPort: 3013
        - containerPort: 3113
        - containerPort: 3014
        - containerPort: 3015
        volumeMounts:
        - name: config
          mountPath: /etc/epoch
        env:
        - name: EPOCH_CONFIG
          value: /etc/epoch/epoch-master.yaml
        livenessProbe:
          httpGet:
            path: /v2/status
            port: 3013
          initialDelaySeconds: 30
          periodSeconds: 300
      volumes:
      - name: config
        configMap:
          name: main-epoch-config

---
apiVersion: v1
kind: Service
metadata:
  name: main-epoch-master
spec:
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  selector:
    app: main-epoch-master

