---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdk-unstable-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ae-node-config
data:
  aeternity.yaml: |
    ---
    peers:
      - "aenode://pp_2oaiqmJnrAVzVkmbgzr4hgFYuqfqtppBVjjh1qMsJhJFvDZqby@3.8.38.115:3015"
    sync:
      port: 3015
      external_port: 3115

    http:
      external:
        port: 3013
      internal:
        port: 3113
        listen_address: 0.0.0.0
        debug_endpoints: true

    websocket:
      channel:
        port: 3014
        listen_address: 0.0.0.0

    keys:
      peer_password: "top secret"
      dir: ./keys

    chain:
      persist: true
      hard_forks:
        "1": 0
        "2": 1

    mining:
      autostart: false
      beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
      beneficiary_reward_delay: 2
      cuckoo:
          edge_bits: 15
          miners:
              - executable: mean15-generic

    fork_management:
      network_id: "ae_unstable"

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ae-node-keys
data:
  peer_key: nygu7kcLnVFSm7c7bCxt5ZZoHTW+IDxc+4ZXphUTNZ0=
  peer_key.pub: 447iAeRHfkA+78ZujyZeRvhyxuYXuI2EFbP0VvVKvPg=
  sign_key: XyspyCDOEDeCBdaqwOGhq7ofLvsQCdQM48ELGMP/200Do9dSK+EWz76VUca+kma7A1G1kQ0ZKayI90yv5NeW6w==
  sign_key.pub: A6PXUivhFs++lVHGvpJmuwNRtZENGSmsiPdMr+TXlus=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ae-node
spec:
  selector:
    matchLabels:
      app: ae-node
  replicas: 1
  template:
    metadata:
      labels:
        app: ae-node
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: ae-node
          image: aeternity/aeternity:minerva
          imagePullPolicy: Always
          ports:
            - containerPort: 3013
            - containerPort: 3015
            - containerPort: 3113
            - containerPort: 3014
          livenessProbe:
            httpGet:
              path: /v2/status
              port: 3013
            initialDelaySeconds: 30
            periodSeconds: 300
          volumeMounts:
            - name: config
              mountPath: /etc/aeternity
            - name: keys
              mountPath: /home/aeternity/node/keys
              readOnly: true
            - name: data
              subPath: logs
              mountPath: /home/aeternity/node/log
            - name: data
              subPath: mnesia
              mountPath: /home/aeternity/node/data/mnesia
          env:
            - name: EPOCH_CONFIG
              value: /etc/aeternity/aeternity.yaml
            - name: AETERNITY_CONFIG # preparing for rename
              value: /etc/aeternity/aeternity.yaml
      volumes:
        - name: config
          configMap:
            name: ae-node-config
        - name: keys
          secret:
            secretName: ae-node-keys
        - name: data
          persistentVolumeClaim:
            claimName: sdk-unstable-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ae-node-service-local
spec:
  ports:
    - name: external
      port: 3013
      targetPort: 3013
      protocol: TCP
    - name: sync
      port: 3015
      targetPort: 3015
      protocol: TCP
    - name: internal
      port: 3113
      targetPort: 3113
      protocol: TCP
    - name: channel
      port: 3014
      targetPort: 3014
      protocol: TCP
  selector:
    app: ae-node

