---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epoch-logs-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-config
data:
  epoch-master.yaml: |
    ---
    peers: []


    sync:
      port: 301
      external_port: 3115

    http:
      external:
        port: 3013
      internal:
        listen_address: 0.0.0.0
      debug: true
    
    websocket:
      channel:
        port: 3014
        listen_address: 0.0.0.0

    keys:
      peer_password: "top secret"
      dir: ./keys

    chain:
      persist: true

    mining:
      beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
      autostart: true
      expected_mine_rate: 180000
      cuckoo:
        miner:
          executable: mean16s-generic
          extra_args: ""
          node_bits: 16
  epoch-miner.yaml: |
    ---
    peers:
    - aenode://pp_HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X@epoch-master:3015


    http:
      external:
        port: 3013
      internal:
        listen_address: 0.0.0.0


    keys:
      peer_password: "top secret"
      dir: ./keys

    chain:
      persist: true

    mining:
      beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
      autostart: true
      expected_mine_rate: 180000
      cuckoo:
        miner:
          executable: mean16s-generic
          extra_args: ""
          node_bits: 16

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: epoch-keys
data:
  peer_key: nygu7kcLnVFSm7c7bCxt5ZZoHTW+IDxc+4ZXphUTNZ0=
  peer_key.pub: 447iAeRHfkA+78ZujyZeRvhyxuYXuI2EFbP0VvVKvPg=
  sign_key: XyspyCDOEDeCBdaqwOGhq7ofLvsQCdQM48ELGMP/200Do9dSK+EWz76VUca+kma7A1G1kQ0ZKayI90yv5NeW6w==
  sign_key.pub: A6PXUivhFs++lVHGvpJmuwNRtZENGSmsiPdMr+TXlus=


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-master
spec:
  selector:
    matchLabels:
      app: epoch-master
  replicas: 1
  template:
    metadata:
      labels:
        app: epoch-master
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: epoch-master
        image: aeternity/epoch:v0.25.0
        ports:
        - containerPort: 3013
        - containerPort: 3015
        - containerPort: 3113
        - containerPort: 3014
        livenessProbe:
          httpGet:
            path: /v2/status
            port: 3013
          initialDelaySeconds: 30
          periodSeconds: 300
        volumeMounts:
        - name: config
          mountPath: /etc/epoch
        - name: keys
          mountPath: /home/epoch/node/keys
          readOnly: true
        - name: logs
          mountPath: /home/epoch/node/log
        env:
        - name: EPOCH_CONFIG
          value: /etc/epoch/epoch-master.yaml
      volumes:
      - name: config
        configMap:
          name: epoch-config
      - name: keys
        secret:
          secretName: epoch-keys
      - name: logs
        persistentVolumeClaim:
          claimName: epoch-logs-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: epoch-master
spec:
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: sync
    port: 3015
    targetPort: 3015
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  - name: channel
    port: 3014
    targetPort: 3014
    protocol: TCP
  selector:
    app: epoch-master

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-miner
spec:
  selector:
    matchLabels:
      app: epoch
  replicas: 2
  template:
    metadata:
      labels:
        app: epoch
    spec:
      containers:
      - name: node
        image: aeternity/epoch:v0.25.0
        ports:
        - containerPort: 3015
        volumeMounts:
        - name: config
          mountPath: /etc/epoch
        env:
        - name: EPOCH_CONFIG
          value: /etc/epoch/epoch-miner.yaml
      volumes:
      - name: config
        configMap:
          name: epoch-config

