---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ae-node-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ae-node-config
data:
  aeternity.yaml: |
    ---
    http:
      external:
        port: 3013
      internal:
        port: 3113
        listen_address: 0.0.0.0
        debug_endpoints: true

    websocket:
      channel:
        port: 3014
        listen_address: 0.0.0.0

    chain:
      persist: true

    mining:
      beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
      autostart: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ae-node
spec:
  selector:
    matchLabels:
      app: ae-node
  replicas: 1
  template:
    metadata:
      labels:
        app: ae-node
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: ae-node
        image: aeternity/aeternity:v1.4.0
        ports:
        - containerPort: 3013
        - containerPort: 3113
        - containerPort: 3014
        - containerPort: 3015
        livenessProbe:
          httpGet:
            path: /v2/status
            port: 3013
          initialDelaySeconds: 30
          periodSeconds: 300
        volumeMounts:
        - name: config
          mountPath: /etc/aeternity
        - name: data
          subPath: logs
          mountPath: /home/aeternity/node/log
        - name: data
          subPath: mnesia
          mountPath: /home/aeternity/node/data/mnesia
        env:
        - name: EPOCH_CONFIG
          value: /etc/aeternity/aeternity.yaml
      volumes:
      - name: config
        configMap:
          name: ae-node-config
      - name: data
        persistentVolumeClaim:
          claimName: ae-node-pvc
      

---
apiVersion: v1
kind: Service
metadata:
  name: ae-node-service
spec:
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  - name: channel
    port: 3014
    targetPort: 3014
    protocol: TCP
  selector:
    app: ae-node
