apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-epoch-config
data:
  epoch-master.yaml: |
    ---
    peers: []

    http:
      external:
        port: 3013
      internal:
        port: 3113
        listen_address: 0.0.0.0
      endpoints:
        debug: true
      debug: true

    websocket:
      channel:
        port: 3014
        listen_address: 0.0.0.0

    keys:
      peer_password: "top secret"
      dir: ./keys

    chain:
      persist: true

    mining:
      autostart: true
      beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
      expected_mine_rate: 4000
      micro_block_cycle: 1000
      cuckoo:
        miner:
          executable: mean15-generic
          extra_args: ""
          edge_bits: 15

    fork_management:
      network_id: "ae_devnet"

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: edge-epoch-keys
data:
  peer_key: nygu7kcLnVFSm7c7bCxt5ZZoHTW+IDxc+4ZXphUTNZ0=
  peer_key.pub: 447iAeRHfkA+78ZujyZeRvhyxuYXuI2EFbP0VvVKvPg=
  sign_key: XyspyCDOEDeCBdaqwOGhq7ofLvsQCdQM48ELGMP/200Do9dSK+EWz76VUca+kma7A1G1kQ0ZKayI90yv5NeW6w==
  sign_key.pub: A6PXUivhFs++lVHGvpJmuwNRtZENGSmsiPdMr+TXlus=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-epoch-master
spec:
  selector:
    matchLabels:
      app: edge-epoch-master
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-epoch-master
    spec:
      containers:
        - name: edge-epoch-master
          image: aeternity/epoch:v1.0.0
          ports:
            - containerPort: 3013
            - containerPort: 3113
            - containerPort: 3014
            - containerPort: 3015
          volumeMounts:
            - name: config
              mountPath: /etc/epoch
            - name: keys
              mountPath: /home/epoch/node/keys
              readOnly: true
          env:
            - name: EPOCH_CONFIG
              value: /etc/epoch/epoch-master.yaml
          livenessProbe:
            httpGet:
              path: /v2/status
              port: 3013
            initialDelaySeconds: 30
            periodSeconds: 300
      volumes:
        - name: config
          configMap:
            name: edge-epoch-config
        - name: keys
          secret:
            secretName: edge-epoch-keys

---
apiVersion: v1
kind: Service
metadata:
  name: edge-epoch-master
spec:
  ports:
    - name: external
      port: 3013
      targetPort: 3013
      protocol: TCP
    - name: sync
      port: 3015
      targetPort: 3015
      protocol: TCP
    - name: internal
      port: 3113
      targetPort: 3113
      protocol: TCP
    - name: channel
      port: 3014
      targetPort: 3014
      protocol: TCP
  selector:
    app: edge-epoch-master
