---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roma-epoch-data-vpc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roma-epoch-config
data:
  epoch-master.yaml: |
    ---
    http:
      external:
        port: 3013
        acceptors: 300
      internal:
        port: 3113
        listen_address: 0.0.0.0
      endpoints:
        debug: true
      debug: true

    websocket:
      channel:
        port: 3014
        listen_address: 0.0.0.0

    chain:
      persist: true

    mining:
      beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
      autostart: false
    regulators:
      http_read:
        # this is for the job queue
        max_size: 200
        counter: 50
        max_time: 0
        rate: 0


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roma-epoch-master
spec:
  selector:
    matchLabels:
      app: roma-epoch-master
  replicas: 1
  template:
    metadata:
      labels:
        app: roma-epoch-master
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: roma-epoch-master
        image: aeternity/epoch:v1.1.0
        ports:
        - containerPort: 3013
        - containerPort: 3113
        - containerPort: 3014
        - containerPort: 3015
        volumeMounts:
        - name: config
          mountPath: /etc/epoch
        - name: data
          subPath: mnesia
          mountPath: /home/epoch/node/data/mnesia
        - name: data
          subPath: log
          mountPath: /home/epoch/node/log
        env:
        - name: EPOCH_CONFIG
          value: /etc/epoch/epoch-master.yaml
        livenessProbe:
          httpGet:
            path: /v2/status
            port: 3013
          initialDelaySeconds: 30
          periodSeconds: 300
      volumes:
      - name: config
        configMap:
          name: roma-epoch-config
      - name: data
        persistentVolumeClaim:
          claimName: roma-epoch-data-vpc

---
apiVersion: v1
kind: Service
metadata:
  name: roma-epoch-master
spec:
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  selector:
    app: roma-epoch-master

