---
apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-config
data:
  epoch-master.yaml: |
    ---
    peers: []

    http:
      external:
        port: 3013
      internal:
        listen_address: 0.0.0.0
      debug: true

    websocket:
      internal:
        listen_address: 0.0.0.0

    keys:
      password: "top secret"
      dir: ./keys

    chain:
      persist: true

    mining:
      beneficiary: "ak$25MZX3BXYP32YDPGWsJqYZ6CgWnqD93VdpCYaTk6KsThEbeFJX"
      autostart: true
      expected_mine_rate: 1200000
      cuckoo:
        miner:
          executable: mean16s-generic
          extra_args: ""
          node_bits: 16
  epoch-miner.yaml: |
    ---
    peers:
    - aenode://pp$HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X@epoch-master:3015

    http:
      external:
        port: 3013
      internal:
        listen_address: 0.0.0.0

    websocket:
      internal:
        listen_address: 0.0.0.0

    keys:
      password: "top secret"
      dir: ./keys

    chain:
      persist: true

    mining:
      beneficiary: "ak$25MZX3BXYP32YDPGWsJqYZ6CgWnqD93VdpCYaTk6KsThEbeFJX"
      autostart: true
      expected_mine_rate: 1200000
      cuckoo:
        miner:
          executable: mean16s-generic
          extra_args: ""
          node_bits: 16

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: epoch-keys
data:
  peer_key: nygu7kcLnVFSm7c7bCxt5ZZoHTW+IDxc+4ZXphUTNZ0=
  peer_key.pub: 447iAeRHfkA+78ZujyZeRvhyxuYXuI2EFbP0VvVKvPg=
  sign_key: XyspyCDOEDeCBdaqwOGhq7ofLvsQCdQM48ELGMP/200Do9dSK+EWz76VUca+kma7A1G1kQ0ZKayI90yv5NeW6w==
  sign_key.pub: A6PXUivhFs++lVHGvpJmuwNRtZENGSmsiPdMr+TXlus=


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-master
spec:
  selector:
    matchLabels:
      app: epoch-master
  replicas: 1
  template:
    metadata:
      labels:
        app: epoch-master
    spec:
      containers:
      - name: epoch-master
        image: aeternity/epoch:v0.20.0
        ports:
        - containerPort: 3013
        - containerPort: 3015
        - containerPort: 3113
        volumeMounts:
        - name: config
          mountPath: /etc/epoch
        - name: keys
          mountPath: /home/epoch/node/keys
          readOnly: true
        env:
        - name: EPOCH_CONFIG
          value: /etc/epoch/epoch-master.yaml
      volumes:
      - name: config
        configMap:
          name: epoch-config
      - name: keys
        secret:
          secretName: epoch-keys

---
apiVersion: v1
kind: Service
metadata:
  name: epoch-service
spec:
  type: LoadBalancer
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  selector:
    app: epoch-master

---
apiVersion: v1
kind: Service
metadata:
  name: epoch-master
spec:
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: sync
    port: 3015
    targetPort: 3015
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  selector:
    app: epoch-master

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-miner
spec:
  selector:
    matchLabels:
      app: epoch
  replicas: 2
  template:
    metadata:
      labels:
        app: epoch
    spec:
      containers:
      - name: node
        image: aeternity/epoch:v0.20.0
        ports:
        - containerPort: 3015
        volumeMounts:
        - name: config
          mountPath: /etc/epoch
        env:
        - name: EPOCH_CONFIG
          value: /etc/epoch/epoch-miner.yaml
      volumes:
      - name: config
        configMap:
          name: epoch-config



