---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdk-testnet-pvc
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-config
data:
  epoch-node.yaml: |
    ---
    peers:
      - "aenode://pp_QU9CvhAQH56a2kA15tCnWPRJ2srMJW8ZmfbbFTAy7eG4o16Bf@52.10.46.160:3015"
      - "aenode://pp_2vhFb3HtHd1S7ynbpbFnEdph1tnDXFSfu4NGtq46S2eM5HCdbC@18.195.109.60:3015"
      - "aenode://pp_27xmgQ4N1E3QwHyoutLtZsHW5DSW4zneQJ3CxT5JbUejxtFuAu@13.250.162.250:3015"
      - "aenode://pp_nt5N7fwae3DW8Mqk4kxkGAnbykRDpEZq9dzzianiMMPo4fJV7@18.130.148.7:3015"

    sync:
      port: 3015
      external_port: 3115

    http:
      external:
        port: 3013
      internal:
        port: 3113
        listen_address: 0.0.0.0
      endpoints:
        debug: true
      debug: true

    websocket:
      channel:
        port: 3014
        listen_address: 0.0.0.0

    keys:
      peer_password: "top secret"
      dir: ./keys

    chain:
      persist: true

    mining:
      autostart: false
      beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"

    fork_management:
      network_id: "ae_uat"


---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: epoch-keys
data:
  peer_key: nygu7kcLnVFSm7c7bCxt5ZZoHTW+IDxc+4ZXphUTNZ0=
  peer_key.pub: 447iAeRHfkA+78ZujyZeRvhyxuYXuI2EFbP0VvVKvPg=
  sign_key: XyspyCDOEDeCBdaqwOGhq7ofLvsQCdQM48ELGMP/200Do9dSK+EWz76VUca+kma7A1G1kQ0ZKayI90yv5NeW6w==
  sign_key.pub: A6PXUivhFs++lVHGvpJmuwNRtZENGSmsiPdMr+TXlus=


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-node
spec:
  selector:
    matchLabels:
      app: epoch-node
  replicas: 1
  template:
    metadata:
      labels:
        app: epoch-node
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: epoch-node
        image: aeternity/epoch:v1.1.0
        ports:
        - containerPort: 3013
        - containerPort: 3015
        - containerPort: 3113
        - containerPort: 3014
        livenessProbe:
          httpGet:
            path: /v2/status
            port: 3013
          initialDelaySeconds: 30
          periodSeconds: 300
        volumeMounts:
        - name: config
          mountPath: /etc/epoch
        - name: keys
          mountPath: /home/epoch/node/keys
          readOnly: true
        - name: data
          subPath: logs
          mountPath: /home/epoch/node/log
        - name: data
          subPath: mnesia
          mountPath: /home/epoch/node/data/mnesia
        env:
        - name: EPOCH_CONFIG
          value: /etc/epoch/epoch-node.yaml
      volumes:
      - name: config
        configMap:
          name: epoch-config
      - name: keys
        secret:
          secretName: epoch-keys
      - name: data
        persistentVolumeClaim:
          claimName: sdk-testnet-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: epoch-node-service-local
spec: 
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: sync
    port: 3015
    targetPort: 3015
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  - name: channel
    port: 3014
    targetPort: 3014
    protocol: TCP
  selector:
    app: epoch-node


---
apiVersion: v1
kind: Service
metadata:
  name: epoch-node-service
spec:
  type: LoadBalancer
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: sync
    port: 3015
    targetPort: 3015
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  - name: channel
    port: 3014
    targetPort: 3014
    protocol: TCP
  selector:
    app: epoch-node
