apiVersion: v1
kind: Pod
metadata:
  name: epoch-master
  labels:
    app: epoch-master
spec:
  containers:
  - name: epoch-master
    image: aeternity/epoch:v0.15.0
    ports:
    - containerPort: 3013
    - containerPort: 3015
    - containerPort: 3113
    volumeMounts:
    - name: config
      mountPath: /etc/epoch
    - name: keys
      mountPath: /home/epoch/node/keys
      readOnly: true
    env:
    - name: EPOCH_CONFIG
      value: /etc/epoch/epoch-master.yaml
  volumes:
  - name: config
    configMap:
      name: epoch-config
  - name: keys
    secret:
      secretName: epoch-keys

---
apiVersion: v1
kind: Service
metadata:
  name: epoch-service
spec:
  type: LoadBalancer
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  selector:
    app: epoch-master

---
apiVersion: v1
kind: Service
metadata:
  name: epoch-master
spec:
  ports:
  - name: external
    port: 3013
    targetPort: 3013
    protocol: TCP
  - name: sync
    port: 3015
    targetPort: 3015
    protocol: TCP
  - name: internal
    port: 3113
    targetPort: 3113
    protocol: TCP
  selector:
    app: epoch-master
