apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-miner
spec:
  selector:
    matchLabels:
      app: epoch
  replicas: 2
  template:
    metadata:
      labels:
        app: epoch
    spec:
      containers:
      - name: node
        image: aeternity/epoch:v0.15.0
        ports:
        - containerPort: 3015
        volumeMounts:
        - name: config
          mountPath: /etc/epoch
        env:
        - name: EPOCH_CONFIG
          value: /etc/epoch/epoch-miner.yaml
      volumes:
      - name: config
        configMap:
          name: epoch-config
